import type { Exercise } from "../../domain";

const createdAt = "2026-09-14T00:00:00.000Z";

export const exerciseCatalog = [
  // ==========================================================
  // JAMBES
  // ==========================================================
  {
    id: "squat",
    name: "Squat barre",
    category: "Musculation",
    zone: "Jambes",
    movement: "Squat",
    equipment: "Barre",
    location: "Salle",
    mode: "series",
    measurementType: "load_reps",
    status: "active",
    createdAt,
    updatedAt: createdAt,
  },
  {
    id: "presse-cuisses",
    name: "Presse à cuisses",
    category: "Musculation",
    zone: "Jambes",
    movement: "Squat",
    equipment: "Machine",
    location: "Salle",
    mode: "series",
    measurementType: "load_reps",
    status: "active",
    createdAt,
    updatedAt: createdAt,
  },
  {
    id: "leg-curl-assis",
    name: "Leg curl assis",
    category: "Musculation",
    zone: "Jambes",
    movement: "Isolation",
    equipment: "Machine",
    location: "Salle",
    mode: "series",
    measurementType: "load_reps",
    status: "active",
    createdAt,
    updatedAt: createdAt,
  },
  {
    id: "hip-thrust",
    name: "Hip thrust",
    category: "Musculation",
    zone: "Jambes",
    movement: "Charnière",
    equipment: "Barre",
    location: "Salle",
    mode: "series",
    measurementType: "load_reps",
    status: "active",
    createdAt,
    updatedAt: createdAt,
  },
  {
    id: "souleve-terre-roumain",
    name: "Soulevé de terre roumain",
    category: "Musculation",
    zone: "Jambes",
    movement: "Charnière",
    equipment: "Barre",
    location: "Salle",
    mode: "series",
    measurementType: "load_reps",
    status: "active",
    createdAt,
    updatedAt: createdAt,
  },

  // ==========================================================
  // DOS
  // ==========================================================
  {
    id: "tirage-vertical",
    name: "Tirage vertical à la poulie",
    category: "Musculation",
    zone: "Dos",
    movement: "Tirage",
    equipment: "Poulie",
    location: "Salle",
    mode: "series",
    measurementType: "load_reps",
    status: "active",
    createdAt,
    updatedAt: createdAt,
  },
  {
    id: "rowing-poulie-basse",
    name: "Rowing poulie basse assis",
    category: "Musculation",
    zone: "Dos",
    movement: "Tirage",
    equipment: "Poulie",
    location: "Salle",
    mode: "series",
    measurementType: "load_reps",
    status: "active",
    createdAt,
    updatedAt: createdAt,
  },
  {
    id: "traction-assistee",
    name: "Traction assistée",
    category: "Musculation",
    zone: "Dos",
    movement: "Tirage",
    equipment: "Machine",
    location: "Salle",
    mode: "series",
    measurementType: "load_reps",
    status: "active",
    createdAt,
    updatedAt: createdAt,
  },
  {
    id: "rowing-haltere-unilateral",
    name: "Rowing haltère unilatéral",
    category: "Musculation",
    zone: "Dos",
    movement: "Tirage",
    equipment: "Haltères",
    location: "Salle",
    mode: "series",
    measurementType: "load_reps",
    status: "active",
    createdAt,
    updatedAt: createdAt,
  },
  {
    id: "pullover-poulie",
    name: "Pullover poulie bras tendus",
    category: "Musculation",
    zone: "Dos",
    movement: "Tirage",
    equipment: "Poulie",
    location: "Salle",
    mode: "series",
    measurementType: "load_reps",
    status: "active",
    createdAt,
    updatedAt: createdAt,
  },

  // ==========================================================
  // PECS
  // ==========================================================
  {
    id: "chest-press",
    name: "Chest press machine",
    category: "Musculation",
    zone: "Pecs",
    movement: "Poussée",
    equipment: "Machine",
    location: "Salle",
    mode: "series",
    measurementType: "load_reps",
    status: "active",
    createdAt,
    updatedAt: createdAt,
  },
  {
    id: "developpe-couche-barre",
    name: "Développé couché barre",
    category: "Musculation",
    zone: "Pecs",
    movement: "Poussée",
    equipment: "Barre",
    location: "Salle",
    mode: "series",
    measurementType: "load_reps",
    status: "active",
    createdAt,
    updatedAt: createdAt,
  },
  {
    id: "developpe-incline-halteres",
    name: "Développé incliné haltères",
    category: "Musculation",
    zone: "Pecs",
    movement: "Poussée",
    equipment: "Haltères",
    location: "Salle",
    mode: "series",
    measurementType: "load_reps",
    status: "active",
    createdAt,
    updatedAt: createdAt,
  },
  {
    id: "ecarte-poulie",
    name: "Écarté à la poulie",
    category: "Musculation",
    zone: "Pecs",
    movement: "Isolation",
    equipment: "Poulie",
    location: "Salle",
    mode: "series",
    measurementType: "load_reps",
    status: "active",
    createdAt,
    updatedAt: createdAt,
  },

  // ==========================================================
  // ÉPAULES
  // ==========================================================
  {
    id: "developpe-epaules-machine",
    name: "Développé épaules machine",
    category: "Musculation",
    zone: "Épaules",
    movement: "Poussée",
    equipment: "Machine",
    location: "Salle",
    mode: "series",
    measurementType: "load_reps",
    status: "active",
    createdAt,
    updatedAt: createdAt,
  },
  {
    id: "developpe-militaire-halteres",
    name: "Développé militaire haltères",
    category: "Musculation",
    zone: "Épaules",
    movement: "Poussée",
    equipment: "Haltères",
    location: "Salle",
    mode: "series",
    measurementType: "load_reps",
    status: "active",
    createdAt,
    updatedAt: createdAt,
  },
  {
    id: "elevations-laterales-halteres",
    name: "Élévations latérales haltères",
    category: "Musculation",
    zone: "Épaules",
    movement: "Isolation",
    equipment: "Haltères",
    location: "Salle",
    mode: "series",
    measurementType: "load_reps",
    status: "active",
    createdAt,
    updatedAt: createdAt,
  },
  {
    id: "face-pull",
    name: "Face pull à la poulie",
    category: "Musculation",
    zone: "Épaules",
    movement: "Tirage",
    equipment: "Poulie",
    location: "Salle",
    mode: "series",
    measurementType: "load_reps",
    status: "active",
    createdAt,
    updatedAt: createdAt,
  },

  // ==========================================================
  // BRAS
  // ==========================================================
  {
    id: "curl-halteres",
    name: "Curl haltères",
    category: "Musculation",
    zone: "Bras",
    movement: "Isolation",
    equipment: "Haltères",
    location: "Salle",
    mode: "series",
    measurementType: "load_reps",
    status: "active",
    createdAt,
    updatedAt: createdAt,
  },
  {
    id: "curl-marteau-halteres",
    name: "Curl marteau haltères",
    category: "Musculation",
    zone: "Bras",
    movement: "Isolation",
    equipment: "Haltères",
    location: "Salle",
    mode: "series",
    measurementType: "load_reps",
    status: "active",
    createdAt,
    updatedAt: createdAt,
  },
  {
    id: "extension-triceps-poulie",
    name: "Extension triceps poulie haute",
    category: "Musculation",
    zone: "Bras",
    movement: "Isolation",
    equipment: "Poulie",
    location: "Salle",
    mode: "series",
    measurementType: "load_reps",
    status: "active",
    createdAt,
    updatedAt: createdAt,
  },
  {
    id: "extension-triceps-dessus-tete",
    name: "Extension triceps au-dessus tête poulie",
    category: "Musculation",
    zone: "Bras",
    movement: "Isolation",
    equipment: "Poulie",
    location: "Salle",
    mode: "series",
    measurementType: "load_reps",
    status: "active",
    createdAt,
    updatedAt: createdAt,
  },

  // ==========================================================
  // CORE
  // ==========================================================
  {
    id: "planche",
    name: "Planche",
    category: "Musculation",
    zone: "Core",
    movement: "Gainage",
    equipment: "Poids du corps",
    location: "Salle",
    mode: "series",
    measurementType: "duration",
    status: "active",
    createdAt,
    updatedAt: createdAt,
  },
  {
    id: "planche-laterale",
    name: "Planche latérale",
    category: "Musculation",
    zone: "Core",
    movement: "Gainage",
    equipment: "Poids du corps",
    location: "Salle",
    mode: "series",
    measurementType: "duration_per_side",
    status: "active",
    createdAt,
    updatedAt: createdAt,
  },
  {
    id: "dead-bug",
    name: "Dead bug",
    category: "Musculation",
    zone: "Core",
    movement: "Gainage",
    equipment: "Poids du corps",
    location: "Maison",
    mode: "series",
    measurementType: "reps_per_side",
    status: "active",
    createdAt,
    updatedAt: createdAt,
  },
  {
    id: "pallof-press",
    name: "Pallof press poulie",
    category: "Musculation",
    zone: "Core",
    movement: "Gainage",
    equipment: "Poulie",
    location: "Salle",
    mode: "series",
    measurementType: "reps_per_side",
    status: "active",
    createdAt,
    updatedAt: createdAt,
  },
  {
    id: "crunch-poulie",
    name: "Crunch poulie",
    category: "Musculation",
    zone: "Core",
    movement: "Isolation",
    equipment: "Poulie",
    location: "Salle",
    mode: "series",
    measurementType: "load_reps",
    status: "active",
    createdAt,
    updatedAt: createdAt,
  },

  // ==========================================================
  // CARDIO
  // ==========================================================
  {
    id: "tapis",
    name: "Tapis de course",
    category: "Cardio",
    equipment: "Tapis",
    location: "Salle",
    mode: "steps",
    measurementType: "duration_speed_incline",
    status: "active",
    createdAt,
    updatedAt: createdAt,
  },
  {
    id: "velo",
    name: "Vélo",
    category: "Cardio",
    equipment: "Vélo",
    location: "Salle",
    mode: "steps",
    measurementType: "duration_distance",
    status: "active",
    createdAt,
    updatedAt: createdAt,
  },
  {
    id: "velo-elliptique",
    name: "Vélo elliptique",
    category: "Cardio",
    equipment: "Vélo elliptique",
    location: "Salle",
    mode: "steps",
    measurementType: "duration_distance",
    status: "active",
    createdAt,
    updatedAt: createdAt,
  },
  {
    id: "rameur",
    name: "Rameur",
    category: "Cardio",
    equipment: "Rameur",
    location: "Salle",
    mode: "steps",
    measurementType: "duration_distance",
    status: "active",
    createdAt,
    updatedAt: createdAt,
  },

  // ==========================================================
  // MOBILITÉ
  // ==========================================================
  {
    id: "mobilite-chat-vache",
    name: "Chat-vache",
    category: "Mobilité",
    location: "Maison",
    mode: "series",
    measurementType: "reps",
    status: "active",
    createdAt,
    updatedAt: createdAt,
  },
  {
    id: "mobilite-rotation-thoracique",
    name: "Rotation thoracique à quatre pattes",
    category: "Mobilité",
    location: "Maison",
    mode: "series",
    measurementType: "reps_per_side",
    status: "active",
    createdAt,
    updatedAt: createdAt,
  },
  {
    id: "mobilite-flechisseur-hanche",
    name: "Étirement fléchisseur hanche en fente",
    category: "Mobilité",
    location: "Maison",
    mode: "series",
    measurementType: "duration_per_side",
    status: "active",
    createdAt,
    updatedAt: createdAt,
  },
  {
    id: "mobilite-ischio-jambiers",
    name: "Étirement ischio-jambiers",
    category: "Mobilité",
    location: "Maison",
    mode: "series",
    measurementType: "duration_per_side",
    status: "active",
    createdAt,
    updatedAt: createdAt,
  },
  {
    id: "mobilite-figure-4",
    name: "Étirement fessier / figure 4",
    category: "Mobilité",
    location: "Maison",
    mode: "series",
    measurementType: "duration_per_side",
    status: "active",
    createdAt,
    updatedAt: createdAt,
  },
  {
    id: "mobilite-cheville-genou-mur",
    name: "Mobilité cheville genou-au-mur",
    category: "Mobilité",
    location: "Maison",
    mode: "series",
    measurementType: "reps_per_side",
    status: "active",
    createdAt,
    updatedAt: createdAt,
  },
  {
    id: "mobilite-ouverture-epaules-mur",
    name: "Ouverture épaules / pectoraux au mur",
    category: "Mobilité",
    location: "Maison",
    mode: "series",
    measurementType: "duration_per_side",
    status: "active",
    createdAt,
    updatedAt: createdAt,
  },
  {
    id: "mobilite-rotation-golf",
    name: "Rotation tronc / hanches spécifique golf",
    category: "Mobilité",
    location: "Maison",
    mode: "series",
    measurementType: "reps_per_side",
    status: "active",
    createdAt,
    updatedAt: createdAt,
  },

  // ==========================================================
  // TESTS DE MOBILITÉ
  // ==========================================================
  {
    id: "test-doigts-sol",
    name: "Doigts-sol",
    category: "Test mobilité",
    location: "Maison",
    mode: "simple",
    measurementType: "distance_cm",
    measurementLabels: {
      value: "Distance doigts-sol",
    },
    status: "active",
    createdAt,
    updatedAt: createdAt,
  },
  {
    id: "test-apley",
    name: "Mains dans le dos",
    category: "Test mobilité",
    location: "Maison",
    mode: "simple",
    measurementType: "distance_cm_per_side",
    measurementLabels: {
      left: "Bras gauche en haut",
      right: "Bras droit en haut",
    },
    status: "active",
    createdAt,
    updatedAt: createdAt,
  },
  {
    id: "test-papillon",
    name: "Papillon",
    category: "Test mobilité",
    location: "Maison",
    mode: "simple",
    measurementType: "distance_cm_per_side",
    measurementLabels: {
      left: "Genou gauche",
      right: "Genou droit",
    },
    status: "active",
    createdAt,
    updatedAt: createdAt,
  },
] satisfies Exercise[];