import type { Exercise } from "../../domain";
import { officialExerciseMedia } from "./exerciseMedia";

const createdAt = "2026-09-14T00:00:00.000Z";

export const exerciseCatalog = [
  // ==========================================================
  // JAMBES
  // ==========================================================
  {
    id: "squat",
    name: "Squat barre",
    category: "Musculation",
    zone: "Jambes",
    movement: "Squat",
    equipment: "Barre",
    progressionGroup: "Quadriceps",
    location: "Salle",
    mode: "series",
    measurementType: "load_reps",
    media: officialExerciseMedia("squat"),
    technique: "Place la barre de façon stable sur le haut du dos. Garde le tronc gainé, descends en contrôlant avec les genoux dans l'axe des pieds, puis remonte en poussant dans le sol.",
    description: "Exercice polyarticulaire de référence pour renforcer les jambes et les fessiers.",
    advice: "Choisis une amplitude que tu contrôles sans perdre la position du dos. Augmente la charge seulement si la technique reste propre.",
    muscles: ["Quadriceps", "Fessiers", "Ischio-jambiers", "Core"],
    status: "active",
    createdAt,
    updatedAt: createdAt,
  },
  {
    id: "presse-cuisses",
    name: "Presse à cuisses",
    category: "Musculation",
    zone: "Jambes",
    movement: "Squat",
    equipment: "Machine",
    progressionGroup: "Quadriceps",
    location: "Salle",
    mode: "series",
    measurementType: "load_reps",
    media: officialExerciseMedia("presse-cuisses"),
    technique: "Place les pieds à largeur confortable sur la plateforme. Descends le chariot de façon contrôlée sans décoller le bassin, puis repousse en gardant les genoux dans l'axe.",
    description: "Mouvement guidé pour travailler principalement les quadriceps et les fessiers avec une grande stabilité.",
    advice: "Ne verrouille pas brutalement les genoux en haut et évite de descendre plus bas que ce que ton bassin peut contrôler.",
    muscles: ["Quadriceps", "Fessiers", "Ischio-jambiers"],
    status: "active",
    createdAt,
    updatedAt: createdAt,
  },
  {
    id: "leg-curl-assis",
    name: "Leg curl assis",
    category: "Musculation",
    zone: "Jambes",
    movement: "Isolation",
    equipment: "Machine",
    progressionGroup: "Ischio-jambiers",
    location: "Salle",
    mode: "series",
    measurementType: "load_reps",
    media: officialExerciseMedia("leg-curl-assis"),
    technique: "Régle la machine pour aligner correctement les genoux avec l'axe de rotation. Ramène les talons vers l'arrière en contrôlant le mouvement, puis reviens lentement.",
    description: "Exercice d'isolation des ischio-jambiers en position assise.",
    advice: "Évite l'élan et garde le bassin plaqué contre le dossier pendant toute la série.",
    muscles: ["Ischio-jambiers"],
    status: "active",
    createdAt,
    updatedAt: createdAt,
  },
  {
    id: "hip-thrust",
    name: "Hip thrust",
    category: "Musculation",
    zone: "Jambes",
    movement: "Charnière",
    equipment: "Barre",
    progressionGroup: "Fessiers",
    location: "Salle",
    mode: "series",
    measurementType: "load_reps",
    media: officialExerciseMedia("hip-thrust"),
    technique: "Appuie le haut du dos sur un banc stable. Pousse les hanches vers le haut jusqu'à aligner épaules, hanches et genoux, puis redescends sous contrôle.",
    description: "Exercice centré sur l'extension de hanche et le renforcement des fessiers.",
    advice: "Évite de cambrer excessivement en haut. Cherche surtout la contraction des fessiers et garde le menton légèrement rentré.",
    muscles: ["Fessiers", "Ischio-jambiers", "Core"],
    status: "active",
    createdAt,
    updatedAt: createdAt,
  },
  {
    id: "souleve-terre-roumain",
    name: "Soulevé de terre roumain",
    category: "Musculation",
    zone: "Jambes",
    movement: "Charnière",
    equipment: "Barre",
    progressionGroup: "Ischio-jambiers",
    location: "Salle",
    mode: "series",
    measurementType: "load_reps",
    media: officialExerciseMedia("souleve-terre-roumain"),
    technique: "Garde la barre près des jambes, fléchis légèrement les genoux et pousse les hanches vers l'arrière en maintenant le dos neutre. Remonte en ramenant les hanches vers l'avant.",
    description: "Exercice de charnière de hanche ciblant fortement la chaîne postérieure.",
    advice: "La descente s'arrête dès que tu ne peux plus reculer les hanches sans arrondir le dos. La charge vient après la qualité du mouvement.",
    muscles: ["Ischio-jambiers", "Fessiers", "Érecteurs du rachis", "Core"],
    status: "active",
    createdAt,
    updatedAt: createdAt,
  },

  // Programme V1 (lot D, conception V2 § 2.5) : sans média tant que
  // les illustrations ne sont pas prêtes.
  {
    id: "montee-banc",
    name: "Montée sur banc bas",
    category: "Musculation",
    zone: "Jambes",
    movement: "Squat",
    equipment: "Poids du corps",
    progressionGroup: "Quadriceps",
    location: "Salle",
    mode: "series",
    measurementType: "reps_per_side",
    technique: "Pose tout le pied sur un banc bas. Pousse dans le talon de la jambe d'appui pour monter sans t'aider de la jambe arrière, puis redescends lentement en contrôlant le genou dans l'axe du pied.",
    description: "Exercice unilatéral qui renforce les quadriceps et les fessiers et améliore l'équilibre sur une jambe.",
    advice: "Choisis une hauteur qui te permet de garder le buste droit et le genou stable. Fais toutes les répétitions d'une jambe, puis change.",
    muscles: ["Quadriceps", "Fessiers", "Ischio-jambiers", "Mollets"],
    status: "active",
    createdAt,
    updatedAt: createdAt,
  },
  {
    id: "chaise-60",
    name: "Chaise contre le mur à 60°",
    category: "Musculation",
    zone: "Jambes",
    movement: "Squat",
    equipment: "Poids du corps",
    progressionGroup: "Quadriceps",
    location: "Salle",
    mode: "series",
    measurementType: "duration",
    technique: "Dos plaqué au mur, descends jusqu'à un angle d'environ 60° aux genoux, pieds à plat et genoux au-dessus des chevilles. Tiens la position sans t'appuyer avec les mains.",
    description: "Gainage des jambes en position basse, utile pour tenir les appuis fléchis du padel.",
    advice: "Garde le même angle d'une séance à l'autre : c'est lui qui rend les durées comparables. Arrête si une douleur apparaît au genou.",
    muscles: ["Quadriceps", "Fessiers"],
    status: "active",
    createdAt,
    updatedAt: createdAt,
  },
  {
    id: "marche-laterale-elastique",
    name: "Marche latérale élastique",
    category: "Musculation",
    zone: "Jambes",
    movement: "Isolation",
    equipment: "Élastique",
    progressionGroup: "Fessiers",
    location: "Salle",
    mode: "series",
    measurementType: "reps_per_side",
    measurementLabels: { value: "pas" },
    technique: "Élastique autour des chevilles ou au-dessus des genoux, fléchis légèrement les jambes. Fais des pas latéraux en gardant l'élastique tendu et le bassin à la même hauteur.",
    description: "Renforcement des fessiers moyens pour la stabilité des déplacements latéraux.",
    advice: "Garde les genoux légèrement fléchis tout du long et ne laisse pas les pieds se rejoindre : l'élastique doit rester tendu.",
    muscles: ["Moyen fessier", "Petit fessier", "Tenseur du fascia lata"],
    status: "active",
    createdAt,
    updatedAt: createdAt,
  },
  {
    id: "mollets-debout",
    name: "Mollets debout",
    category: "Musculation",
    zone: "Jambes",
    movement: "Isolation",
    equipment: "Machine",
    location: "Salle",
    mode: "series",
    measurementType: "load_reps",
    technique: "Avant du pied sur la marche, talons dans le vide. Monte le plus haut possible sur la pointe des pieds, marque un temps, puis redescends lentement sous l'horizontale.",
    description: "Renforcement des mollets, utile pour les appuis et les changements de direction.",
    advice: "Cherche l'amplitude complète plutôt que la charge. Évite de rebondir en bas du mouvement.",
    muscles: ["Gastrocnémiens", "Soléaire"],
    status: "active",
    createdAt,
    updatedAt: createdAt,
  },

  // ==========================================================
  // DOS
  // ==========================================================
  {
    id: "tirage-vertical",
    name: "Tirage vertical à la poulie",
    category: "Musculation",
    zone: "Dos",
    movement: "Tirage",
    equipment: "Poulie",
    progressionGroup: "Dos",
    movementFamily: "tirage_vertical",
    location: "Salle",
    mode: "series",
    measurementType: "load_reps",
    media: officialExerciseMedia("tirage-vertical"),
    technique: "Assieds-toi stable, poitrine légèrement sortie. Tire la barre vers le haut de la poitrine en abaissant les épaules et en ramenant les coudes vers le bas, puis remonte sous contrôle.",
    description: "Exercice de tirage vertical destiné principalement au développement du grand dorsal.",
    advice: "Évite de tirer derrière la nuque ou de transformer le mouvement en balancement du buste. Pense à conduire le mouvement avec les coudes.",
    muscles: ["Grand dorsal", "Biceps", "Rhomboïdes", "Trapèzes"],
    status: "active",
    createdAt,
    updatedAt: createdAt,
  },
  {
    id: "rowing-poulie-basse",
    name: "Rowing poulie basse assis",
    category: "Musculation",
    zone: "Dos",
    movement: "Tirage",
    equipment: "Poulie",
    progressionGroup: "Dos",
    movementFamily: "tirage_horizontal",
    location: "Salle",
    mode: "series",
    measurementType: "load_reps",
    media: officialExerciseMedia("rowing-poulie-basse"),
    technique: "Garde le buste stable et le dos neutre. Tire la poignée vers le bas du ventre en ramenant les coudes derrière toi, puis tends les bras progressivement sans arrondir excessivement le dos.",
    description: "Tirage horizontal permettant de renforcer le dos avec une tension régulière.",
    advice: "Ne donne pas d'élan avec le buste. Termine le tirage en rapprochant les omoplates plutôt qu'en tirant uniquement avec les bras.",
    muscles: ["Grand dorsal", "Rhomboïdes", "Trapèzes", "Biceps"],
    status: "active",
    createdAt,
    updatedAt: createdAt,
  },
  {
    id: "traction-assistee",
    name: "Traction assistée",
    category: "Musculation",
    zone: "Dos",
    movement: "Tirage",
    equipment: "Machine",
    progressionGroup: "Dos",
    movementFamily: "tirage_vertical",
    location: "Salle",
    mode: "series",
    measurementType: "load_reps",
    loadSemantics: "assistance",
    media: officialExerciseMedia("traction-assistee"),
    technique: "Place-toi correctement sur l'assistance, commence bras tendus et épaules contrôlées. Tire le corps vers le haut jusqu'à rapprocher la poitrine de la barre, puis redescends lentement.",
    description: "Version assistée de la traction permettant de développer progressivement la force nécessaire à une traction au poids du corps.",
    advice: "Utilise juste assez d'assistance pour conserver une amplitude complète et une exécution propre. Réduis progressivement l'assistance au fil de ta progression.",
    muscles: ["Grand dorsal", "Biceps", "Rhomboïdes", "Core"],
    status: "active",
    createdAt,
    updatedAt: createdAt,
  },
  {
    id: "traction-negative",
    name: "Traction négative",
    category: "Musculation",
    zone: "Dos",
    movement: "Tirage",
    equipment: "Poids du corps",
    progressionGroup: "Dos",
    movementFamily: "tirage_vertical",
    location: "Salle",
    mode: "series",
    measurementType: "reps_duration",
    technique: "Monte en haut de la barre à l'aide d'un banc ou d'un saut, menton au-dessus de la barre. Descends le plus lentement possible jusqu'aux bras tendus, épaules engagées, puis remets-toi en haut sans tirer.",
    description: "Traction en phase de descente seulement, pour construire la force de la traction complète.",
    advice: "Vise une descente d'au moins 5 secondes. Note la durée de chaque descente : c'est elle qui montre le progrès.",
    muscles: ["Grand dorsal", "Biceps", "Rhomboïdes", "Core"],
    status: "active",
    createdAt,
    updatedAt: createdAt,
  },
  {
    id: "suspension-omoplates",
    name: "Suspension + activation des omoplates",
    category: "Musculation",
    zone: "Dos",
    movement: "Tirage",
    equipment: "Poids du corps",
    progressionGroup: "Dos",
    movementFamily: "tirage_vertical",
    location: "Salle",
    mode: "series",
    measurementType: "duration",
    technique: "Suspends-toi à la barre bras tendus. Abaisse et rapproche les omoplates sans plier les coudes, tiens, relâche légèrement, puis recommence pendant toute la durée.",
    description: "Suspension active qui prépare les épaules et le haut du dos aux tractions.",
    advice: "Les bras restent tendus : le mouvement vient des omoplates. Garde les jambes serrées et le tronc gainé.",
    muscles: ["Trapèzes inférieurs", "Grand dorsal", "Avant-bras"],
    status: "active",
    createdAt,
    updatedAt: createdAt,
  },
  {
    id: "rowing-haltere-unilateral",
    name: "Rowing haltère unilatéral",
    category: "Musculation",
    zone: "Dos",
    movement: "Tirage",
    equipment: "Haltères",
    progressionGroup: "Dos",
    movementFamily: "tirage_horizontal",
    location: "Salle",
    mode: "series",
    measurementType: "load_reps",
    media: officialExerciseMedia("rowing-haltere-unilateral"),
    technique: "Stabilise le tronc avec un appui solide. Tire l'haltère vers la hanche en gardant le coude près du corps, puis redescends jusqu'à tendre le bras sans tourner excessivement le buste.",
    description: "Tirage horizontal unilatéral permettant de travailler chaque côté du dos séparément.",
    advice: "Garde le bassin et les épaules aussi stables que possible. Ne cherche pas à monter l'haltère plus haut en faisant pivoter le tronc.",
    muscles: ["Grand dorsal", "Rhomboïdes", "Trapèzes", "Biceps"],
    status: "active",
    createdAt,
    updatedAt: createdAt,
  },
  {
    id: "pullover-poulie",
    name: "Pullover poulie bras tendus",
    category: "Musculation",
    zone: "Dos",
    movement: "Tirage",
    equipment: "Poulie",
    progressionGroup: "Dos",
    location: "Salle",
    mode: "series",
    measurementType: "load_reps",
    media: officialExerciseMedia("pullover-poulie"),
    technique: "Place-toi face à la poulie haute, bras presque tendus et tronc stable. Abaisse la barre ou la corde vers les cuisses en gardant les coudes légèrement fléchis, puis remonte lentement.",
    description: "Exercice à la poulie sollicitant le grand dorsal avec peu de flexion du coude.",
    advice: "Évite de transformer le mouvement en extension de triceps ou de cambrer le dos pour gagner de l'amplitude.",
    muscles: ["Grand dorsal", "Grand rond", "Triceps"],
    status: "active",
    createdAt,
    updatedAt: createdAt,
  },

  // ==========================================================
  // PECS
  // ==========================================================
  {
    id: "chest-press",
    name: "Chest press machine",
    category: "Musculation",
    zone: "Pecs",
    movement: "Poussée",
    equipment: "Machine",
    progressionGroup: "Pectoraux",
    movementFamily: "poussee_horizontale",
    location: "Salle",
    mode: "series",
    measurementType: "load_reps",
    media: officialExerciseMedia("chest-press"),
    technique: "Régle le siège pour placer les poignées approximativement à hauteur de poitrine. Garde le dos contre le dossier, pousse les poignées devant toi puis reviens lentement sans laisser les épaules partir vers l'avant.",
    description: "Mouvement guidé de poussée pour renforcer principalement les pectoraux.",
    advice: "Garde les épaules basses et stables. Ne verrouille pas brutalement les coudes en fin de poussée.",
    muscles: ["Pectoraux", "Triceps", "Deltoïdes antérieurs"],
    status: "active",
    createdAt,
    updatedAt: createdAt,
  },
  {
    id: "developpe-couche-barre",
    name: "Développé couché barre",
    category: "Musculation",
    zone: "Pecs",
    movement: "Poussée",
    equipment: "Barre",
    progressionGroup: "Pectoraux",
    movementFamily: "poussee_horizontale",
    location: "Salle",
    mode: "series",
    measurementType: "load_reps",
    media: officialExerciseMedia("developpe-couche-barre"),
    technique: "Allonge-toi avec les pieds stables au sol. Descends la barre de façon contrôlée vers le bas de la poitrine, puis repousse-la en gardant les omoplates stables sur le banc.",
    description: "Exercice polyarticulaire classique de poussée horizontale pour développer les pectoraux.",
    advice: "Utilise une prise confortable et garde les poignets alignés avec les avant-bras. Avec une charge importante, utilise des sécurités ou un partenaire.",
    muscles: ["Pectoraux", "Triceps", "Deltoïdes antérieurs"],
    status: "active",
    createdAt,
    updatedAt: createdAt,
  },
  {
    id: "developpe-incline-halteres",
    name: "Développé incliné haltères",
    category: "Musculation",
    zone: "Pecs",
    movement: "Poussée",
    equipment: "Haltères",
    progressionGroup: "Pectoraux",
    movementFamily: "poussee_horizontale",
    location: "Salle",
    mode: "series",
    measurementType: "load_reps",
    media: officialExerciseMedia("developpe-incline-halteres"),
    technique: "Installe-toi sur un banc légèrement incliné, haltères près de la poitrine. Pousse-les vers le haut en gardant les épaules stables, puis redescends sous contrôle.",
    description: "Variante inclinée du développé sollicitant particulièrement la partie supérieure des pectoraux.",
    advice: "Une inclinaison modérée suffit. Évite de transformer le mouvement en développé épaules en relevant trop fortement le dossier.",
    muscles: ["Pectoraux", "Deltoïdes antérieurs", "Triceps"],
    status: "active",
    createdAt,
    updatedAt: createdAt,
  },
  {
    id: "ecarte-poulie",
    name: "Écarté à la poulie",
    category: "Musculation",
    zone: "Pecs",
    movement: "Isolation",
    equipment: "Poulie",
    progressionGroup: "Pectoraux",
    location: "Salle",
    mode: "series",
    measurementType: "load_reps",
    media: officialExerciseMedia("ecarte-poulie"),
    technique: "Place-toi de façon stable entre les poulies, coudes légèrement fléchis. Rapproche les mains devant la poitrine en conservant l'angle des coudes, puis ouvre lentement jusqu'à une amplitude confortable.",
    description: "Exercice d'isolation des pectoraux utilisant la tension continue des poulies.",
    advice: "Travaille avec une charge permettant de contrôler toute l'amplitude. Ne cherche pas à étirer excessivement les épaules en position ouverte.",
    muscles: ["Pectoraux", "Deltoïdes antérieurs"],
    status: "active",
    createdAt,
    updatedAt: createdAt,
  },
  {
    id: "pompes",
    name: "Pompes",
    category: "Musculation",
    zone: "Pecs",
    movement: "Poussée",
    equipment: "Poids du corps",
    progressionGroup: "Pectoraux",
    movementFamily: "poussee_horizontale",
    location: "Maison",
    mode: "series",
    measurementType: "reps",
    media: officialExerciseMedia("pompes"),
    technique: "Mains au sol un peu plus larges que les épaules, corps aligné de la tête aux talons. Descends en fléchissant les coudes jusqu'à frôler le sol avec la poitrine, puis repousse sans casser l'alignement du bassin.",
    description: "Exercice de poussée au poids du corps, réalisable partout, qui sollicite pectoraux, triceps et gainage.",
    advice: "Si la version au sol est trop dure, surélève les mains (banc, marche) ; si elle devient facile, ralentis la descente ou surélève les pieds. Garde les coudes à environ 45° du corps.",
    muscles: ["Pectoraux", "Triceps", "Deltoïdes antérieurs", "Core"],
    status: "active",
    createdAt,
    updatedAt: createdAt,
  },

  // ==========================================================
  // ÉPAULES
  // ==========================================================
  {
    id: "developpe-epaules-machine",
    name: "Développé épaules machine",
    category: "Musculation",
    zone: "Épaules",
    movement: "Poussée",
    equipment: "Machine",
    progressionGroup: "Épaules",
    movementFamily: "poussee_verticale",
    location: "Salle",
    mode: "series",
    measurementType: "load_reps",
    media: officialExerciseMedia("developpe-epaules-machine"),
    technique: "Régle le siège pour placer les poignées à hauteur confortable des épaules. Garde le dos contre le dossier, pousse vers le haut sans hausser les épaules, puis redescends lentement.",
    description: "Mouvement guidé de poussée verticale destiné principalement au renforcement des épaules.",
    advice: "Choisis une amplitude confortable pour les épaules et évite de cambrer le bas du dos pour terminer les répétitions.",
    muscles: ["Deltoïdes", "Triceps", "Trapèzes"],
    status: "active",
    createdAt,
    updatedAt: createdAt,
  },
  {
    id: "developpe-militaire-halteres",
    name: "Développé militaire haltères",
    category: "Musculation",
    zone: "Épaules",
    movement: "Poussée",
    equipment: "Haltères",
    progressionGroup: "Épaules",
    movementFamily: "poussee_verticale",
    location: "Salle",
    mode: "series",
    measurementType: "load_reps",
    media: officialExerciseMedia("developpe-militaire-halteres"),
    technique: "Tiens les haltères de chaque côté des épaules avec le tronc gainé. Pousse-les au-dessus de la tête puis redescends de façon contrôlée jusqu'à la position de départ.",
    description: "Exercice de poussée verticale aux haltères pour développer la force et la masse musculaire des épaules.",
    advice: "Garde les côtes contrôlées et évite de compenser par une forte cambrure lombaire. Utilise une charge permettant une trajectoire stable.",
    muscles: ["Deltoïdes", "Triceps", "Trapèzes"],
    status: "active",
    createdAt,
    updatedAt: createdAt,
  },
  {
    id: "elevations-laterales-halteres",
    name: "Élévations latérales haltères",
    category: "Musculation",
    zone: "Épaules",
    movement: "Isolation",
    equipment: "Haltères",
    progressionGroup: "Épaules",
    location: "Salle",
    mode: "series",
    measurementType: "load_reps",
    media: officialExerciseMedia("elevations-laterales-halteres"),
    technique: "Tiens les haltères le long du corps avec les coudes légèrement fléchis. Élève les bras sur les côtés jusqu'à environ hauteur des épaules, puis redescends lentement.",
    description: "Exercice d'isolation ciblant principalement la partie latérale des épaules.",
    advice: "Utilise une charge modérée et évite de donner de l'élan avec le corps ou de hausser excessivement les épaules.",
    muscles: ["Deltoïdes latéraux", "Trapèzes"],
    status: "active",
    createdAt,
    updatedAt: createdAt,
  },
  {
    id: "face-pull",
    name: "Face pull à la poulie",
    category: "Musculation",
    zone: "Épaules",
    movement: "Tirage",
    equipment: "Poulie",
    progressionGroup: "Épaules",
    movementFamily: "tirage_horizontal",
    location: "Salle",
    mode: "series",
    measurementType: "load_reps",
    media: officialExerciseMedia("face-pull"),
    technique: "Place la corde sur une poulie haute. Tire-la vers le visage en écartant les mains et en ramenant les coudes vers l'arrière, puis reviens lentement.",
    description: "Tirage à la corde sollicitant l'arrière des épaules et les muscles du haut du dos.",
    advice: "Privilégie le contrôle à la charge. Garde les épaules basses et termine le mouvement sans avancer la tête vers la corde.",
    muscles: ["Deltoïdes postérieurs", "Rhomboïdes", "Trapèzes", "Coiffe des rotateurs"],
    status: "active",
    createdAt,
    updatedAt: createdAt,
  },

  // ==========================================================
  // BRAS
  // ==========================================================
  {
    id: "curl-halteres",
    name: "Curl haltères",
    category: "Musculation",
    zone: "Bras",
    movement: "Isolation",
    equipment: "Haltères",
    progressionGroup: "Bras",
    location: "Salle",
    mode: "series",
    measurementType: "load_reps",
    media: officialExerciseMedia("curl-halteres"),
    technique: "Tiens les haltères bras le long du corps, paumes vers l'avant. Fléchis les coudes pour monter les haltères sans déplacer les bras vers l'avant, puis redescends lentement.",
    description: "Exercice classique d'isolation pour renforcer les muscles fléchisseurs du coude.",
    advice: "Garde les coudes près du corps et évite de prendre de l'élan avec le dos. Contrôle particulièrement la descente.",
    muscles: ["Biceps", "Brachial", "Avant-bras"],
    status: "active",
    createdAt,
    updatedAt: createdAt,
  },
  {
    id: "curl-marteau-halteres",
    name: "Curl marteau haltères",
    category: "Musculation",
    zone: "Bras",
    movement: "Isolation",
    equipment: "Haltères",
    progressionGroup: "Bras",
    location: "Salle",
    mode: "series",
    measurementType: "load_reps",
    media: officialExerciseMedia("curl-marteau-halteres"),
    technique: "Tiens les haltères avec les paumes face à face. Fléchis les coudes en conservant cette prise neutre, puis redescends sous contrôle jusqu'à presque tendre les bras.",
    description: "Variante du curl réalisée en prise neutre, sollicitant fortement le brachial et les avant-bras.",
    advice: "Garde les poignets neutres et les coudes stables. Ne balance pas le buste pour terminer les répétitions.",
    muscles: ["Brachial", "Biceps", "Brachio-radial", "Avant-bras"],
    status: "active",
    createdAt,
    updatedAt: createdAt,
  },
  {
    id: "extension-triceps-poulie",
    name: "Extension triceps poulie haute",
    category: "Musculation",
    zone: "Bras",
    movement: "Isolation",
    equipment: "Poulie",
    progressionGroup: "Bras",
    location: "Salle",
    mode: "series",
    measurementType: "load_reps",
    media: officialExerciseMedia("extension-triceps-poulie"),
    technique: "Place les coudes près du corps et garde-les fixes. Pousse la poignée ou la corde vers le bas jusqu'à tendre les bras, puis remonte lentement sans laisser les coudes avancer.",
    description: "Exercice d'isolation à la poulie pour renforcer les triceps.",
    advice: "Évite d'utiliser le poids du corps pour pousser la charge. Seuls les avant-bras doivent principalement bouger.",
    muscles: ["Triceps"],
    status: "active",
    createdAt,
    updatedAt: createdAt,
  },
  {
    id: "extension-triceps-dessus-tete",
    name: "Extension triceps au-dessus tête poulie",
    category: "Musculation",
    zone: "Bras",
    movement: "Isolation",
    equipment: "Poulie",
    progressionGroup: "Bras",
    location: "Salle",
    mode: "series",
    measurementType: "load_reps",
    media: officialExerciseMedia("extension-triceps-dessus-tete"),
    technique: "Place-toi dos à la poulie avec les bras au-dessus de la tête. Garde les coudes orientés vers l'avant, tends les bras puis reviens lentement en contrôlant la flexion.",
    description: "Extension des triceps au-dessus de la tête permettant notamment de solliciter leur longue portion.",
    advice: "Garde le tronc gainé et évite de cambrer le bas du dos. Réduis la charge si les coudes s'écartent fortement.",
    muscles: ["Triceps"],
    status: "active",
    createdAt,
    updatedAt: createdAt,
  },
  {
    id: "import-curl-biceps-ez",
    name: "Curl biceps barre EZ",
    category: "Musculation",
    zone: "Bras",
    movement: "Isolation",
    equipment: "Barre",
    progressionGroup: "Bras",
    location: "Salle",
    mode: "series",
    measurementType: "load_reps",
    media: officialExerciseMedia("import-curl-biceps-ez"),
    technique: "Debout, pieds largeur de bassin, saisis la barre EZ sur les prises inclinées, paumes vers le haut, bras tendus le long du corps. Fléchis les coudes pour monter la barre jusqu'aux épaules sans avancer les coudes, puis redescends lentement jusqu'à l'extension complète.",
    description: "Isolation des fléchisseurs du coude avec une barre EZ : la prise inclinée soulage les poignets par rapport à une barre droite.",
    advice: "Coudes collés au corps, buste immobile, aucun élan avec le dos. Descente contrôlée sur 2 à 3 secondes ; commence à vide pour caler le geste.",
    muscles: ["Biceps", "Brachial", "Avant-bras"],
    status: "active",
    createdAt,
    updatedAt: createdAt,
  },
  {
    id: "dips-assistes",
    name: "Dips assistés",
    category: "Musculation",
    zone: "Bras",
    movement: "Poussée",
    equipment: "Machine",
    progressionGroup: "Bras",
    movementFamily: "poussee_verticale",
    location: "Salle",
    mode: "series",
    measurementType: "load_reps",
    loadSemantics: "assistance",
    media: officialExerciseMedia("dips-assistes"),
    technique: "Place les genoux ou les pieds sur l'assistance, mains sur les barres parallèles, bras tendus. Descends en fléchissant les coudes jusqu'à ce que les épaules arrivent à hauteur des coudes, puis repousse jusqu'à tendre les bras.",
    description: "Version assistée des dips, poussée verticale dominée par les triceps, permettant de construire progressivement la force nécessaire aux dips au poids du corps.",
    advice: "La charge indiquée est l'assistance : plus elle est élevée, plus l'exercice est facile. Réduis-la progressivement en gardant une amplitude complète et les épaules basses.",
    muscles: ["Triceps", "Pectoraux", "Deltoïdes antérieurs"],
    status: "active",
    createdAt,
    updatedAt: createdAt,
  },

  // ==========================================================
  // CORE
  // ==========================================================
  {
    id: "planche",
    name: "Planche",
    category: "Musculation",
    zone: "Core",
    movement: "Gainage",
    equipment: "Poids du corps",
    progressionGroup: "Abdominaux",
    location: "Salle",
    mode: "series",
    measurementType: "duration",
    media: officialExerciseMedia("planche"),
    technique: "Place les avant-bras au sol, coudes sous les épaules. Tends les jambes et maintiens le corps aligné de la tête aux talons en contractant les abdominaux et les fessiers.",
    description: "Exercice de gainage statique destiné à renforcer la stabilité du tronc.",
    advice: "Garde une respiration régulière. Arrête la série lorsque tu ne peux plus maintenir le bassin et le dos dans une position stable.",
    muscles: ["Abdominaux", "Transverse", "Fessiers", "Épaules"],
    status: "active",
    createdAt,
    updatedAt: createdAt,
  },
  {
    id: "planche-laterale",
    name: "Planche latérale",
    category: "Musculation",
    zone: "Core",
    movement: "Gainage",
    equipment: "Poids du corps",
    progressionGroup: "Abdominaux",
    location: "Salle",
    mode: "series",
    measurementType: "duration_per_side",
    media: officialExerciseMedia("planche-laterale"),
    technique: "Place l'avant-bras au sol avec le coude sous l'épaule. Soulève le bassin et maintiens la tête, le tronc et les jambes alignés sans laisser le bassin descendre.",
    description: "Gainage latéral sollicitant particulièrement les muscles responsables de la stabilité du tronc.",
    advice: "Cherche un alignement stable plutôt qu'une durée maximale. Réalise les deux côtés séparément.",
    muscles: ["Obliques", "Transverse", "Moyen fessier", "Épaules"],
    status: "active",
    createdAt,
    updatedAt: createdAt,
  },
  {
    id: "dead-bug",
    name: "Dead bug",
    category: "Musculation",
    zone: "Core",
    movement: "Gainage",
    equipment: "Poids du corps",
    progressionGroup: "Abdominaux",
    location: "Maison",
    mode: "series",
    measurementType: "reps_per_side",
    media: officialExerciseMedia("dead-bug"),
    technique: "Allonge-toi sur le dos, hanches et genoux fléchis à environ 90 degrés et bras dirigés vers le plafond. Éloigne lentement un bras et la jambe opposée sans perdre le contrôle du bassin, puis alterne.",
    description: "Exercice de contrôle du tronc associant mouvements alternés des bras et des jambes.",
    advice: "Réduis l'amplitude dès que le bas du dos commence à perdre sa position. La priorité est le contrôle, pas la vitesse.",
    muscles: ["Abdominaux", "Transverse", "Fléchisseurs de hanche"],
    status: "active",
    createdAt,
    updatedAt: createdAt,
  },
  {
    id: "pallof-press",
    name: "Pallof press poulie",
    category: "Musculation",
    zone: "Core",
    movement: "Gainage",
    equipment: "Poulie",
    progressionGroup: "Abdominaux",
    location: "Salle",
    mode: "series",
    measurementType: "reps_per_side",
    media: officialExerciseMedia("pallof-press"),
    technique: "Place-toi de côté par rapport à la poulie et tiens la poignée devant la poitrine. Tends les bras devant toi sans laisser le tronc pivoter, puis ramène les mains vers la poitrine.",
    description: "Exercice anti-rotation destiné à renforcer la capacité du tronc à résister aux forces de rotation.",
    advice: "Utilise une charge permettant de garder les épaules et le bassin face à l'avant. Évite de compenser en tournant le corps.",
    muscles: ["Obliques", "Transverse", "Abdominaux", "Fessiers"],
    status: "active",
    createdAt,
    updatedAt: createdAt,
  },
  {
    id: "crunch-poulie",
    name: "Crunch poulie",
    category: "Musculation",
    zone: "Core",
    movement: "Isolation",
    equipment: "Poulie",
    progressionGroup: "Abdominaux",
    location: "Salle",
    mode: "series",
    measurementType: "load_reps",
    media: officialExerciseMedia("crunch-poulie"),
    technique: "Agenouille-toi face à la poulie haute en tenant la corde près de la tête. Enroule le tronc en rapprochant les côtes du bassin, puis remonte lentement sans tirer principalement avec les bras.",
    description: "Exercice de flexion du tronc à la poulie permettant de travailler les abdominaux avec une résistance réglable.",
    advice: "Garde les hanches relativement stables et choisis une charge qui permet de contrôler l'enroulement du tronc.",
    muscles: ["Grand droit de l'abdomen", "Obliques"],
    status: "active",
    createdAt,
    updatedAt: createdAt,
  },

  /* Lot K.0 (25/09/2026) : exercices des routines du soir absents du catalogue. */
  {
    id: "bird-dog",
    name: "Bird dog",
    category: "Musculation",
    zone: "Core",
    movement: "Gainage",
    equipment: "Poids du corps",
    progressionGroup: "Abdominaux",
    location: "Maison",
    mode: "series",
    measurementType: "reps_per_side",
    technique: "À quatre pattes, mains sous les épaules et genoux sous les hanches. Allonge lentement un bras devant et la jambe opposée derrière, marque un temps d'arrêt, puis reviens et alterne.",
    description: "Exercice de stabilité du tronc et du dos, bras et jambe opposés.",
    advice: "Garde le bassin immobile et le dos plat : le mouvement doit rester lent et contrôlé.",
    muscles: ["Lombaires", "Transverse", "Fessiers", "Épaules"],
    status: "active",
    createdAt,
    updatedAt: createdAt,
  },

  {
    id: "crunch-inverse",
    name: "Crunch inversé",
    category: "Musculation",
    zone: "Core",
    movement: "Isolation",
    equipment: "Poids du corps",
    progressionGroup: "Abdominaux",
    location: "Maison",
    mode: "series",
    measurementType: "reps",
    technique: "Allongé sur le dos, genoux fléchis au-dessus des hanches, bras le long du corps. Enroule le bassin pour décoller légèrement les fesses du sol, puis redescends lentement.",
    description: "Exercice d'abdominaux qui enroule le bassin vers la poitrine.",
    advice: "Le mouvement vient du bassin, pas de l'élan des jambes. Redescends sans cambrer le bas du dos.",
    muscles: ["Grand droit de l'abdomen", "Transverse"],
    status: "active",
    createdAt,
    updatedAt: createdAt,
  },

  {
    id: "hollow-body-genoux",
    name: "Hollow body genoux fléchis",
    category: "Musculation",
    zone: "Core",
    movement: "Gainage",
    equipment: "Poids du corps",
    progressionGroup: "Abdominaux",
    location: "Maison",
    mode: "series",
    measurementType: "duration",
    technique: "Allongé sur le dos, plaque le bas du dos au sol, décolle les épaules et garde les genoux fléchis au-dessus des hanches. Tiens la position en respirant.",
    description: "Gainage de l'avant du tronc, version genoux fléchis.",
    advice: "Le bas du dos reste collé au sol : dès qu'il se décolle, la série s'arrête.",
    muscles: ["Grand droit de l'abdomen", "Transverse"],
    status: "active",
    createdAt,
    updatedAt: createdAt,
  },

  // ==========================================================
  // CARDIO
  // ==========================================================
  {
    id: "tapis",
    name: "Tapis de course",
    category: "Cardio",
    equipment: "Tapis",
    location: "Salle",
    mode: "steps",
    measurementType: "duration_speed_incline",
    media: officialExerciseMedia("tapis"),
    technique: "Marche ou cours au centre du tapis avec une posture naturelle, le regard vers l'avant et les épaules relâchées. Laisse les bras accompagner le mouvement sans t'appuyer sur les poignées.",
    description: "Appareil cardio permettant de travailler la marche, la course, la vitesse et l'inclinaison avec des réglages précis.",
    advice: "Augmente progressivement la vitesse ou la pente. Utilise les poignées uniquement pour monter, descendre ou te sécuriser.",
    muscles: ["Quadriceps", "Ischio-jambiers", "Fessiers", "Mollets", "Cardio-respiratoire"],
    status: "active",
    createdAt,
    updatedAt: createdAt,
  },
  {
    id: "velo",
    name: "Vélo",
    category: "Cardio",
    equipment: "Vélo",
    location: "Salle",
    mode: "steps",
    measurementType: "duration_distance",
    media: officialExerciseMedia("velo"),
    technique: "Régle la selle pour conserver une légère flexion du genou lorsque la pédale est en position basse. Pédale de façon fluide en gardant le bassin stable.",
    description: "Appareil cardio à faible impact permettant de travailler l'endurance avec une résistance réglable.",
    advice: "Évite une selle trop basse et choisis une résistance qui permet de conserver un pédalage régulier.",
    muscles: ["Quadriceps", "Ischio-jambiers", "Fessiers", "Mollets", "Cardio-respiratoire"],
    status: "active",
    createdAt,
    updatedAt: createdAt,
  },
  {
    id: "sprint-velo",
    name: "Sprints vélo",
    category: "Cardio",
    equipment: "Vélo",
    location: "Salle",
    mode: "series",
    measurementType: "duration_power",
    technique: "Sur un vélo réglé comme d'habitude, pédale à fond pendant toute la durée du sprint, puis récupère en pédalant très doucement jusqu'au suivant.",
    description: "Efforts courts et maximaux pour l'explosivité des jambes : chaque sprint se note en watts ou en mètres.",
    advice: "Garde le même vélo et la même résistance d'une séance à l'autre : sinon les résultats ne se comparent pas. L'unité est fixée au premier sprint noté.",
    muscles: ["Quadriceps", "Fessiers", "Ischio-jambiers", "Mollets"],
    status: "active",
    createdAt,
    updatedAt: createdAt,
  },
  {
    id: "velo-elliptique",
    name: "Vélo elliptique",
    category: "Cardio",
    equipment: "Vélo elliptique",
    location: "Salle",
    mode: "steps",
    measurementType: "duration_distance",
    media: officialExerciseMedia("velo-elliptique"),
    technique: "Pose entièrement les pieds sur les pédales et maintiens une posture droite. Pousse et tire les poignées en coordination avec les jambes tout en gardant un mouvement fluide.",
    description: "Appareil cardio combinant le mouvement des jambes et des bras avec peu d'impact articulaire.",
    advice: "Évite de te suspendre aux poignées. Commence avec une résistance modérée avant d'augmenter l'intensité.",
    muscles: ["Quadriceps", "Fessiers", "Ischio-jambiers", "Bras", "Cardio-respiratoire"],
    status: "active",
    createdAt,
    updatedAt: createdAt,
  },
  {
    id: "rameur",
    name: "Rameur",
    category: "Cardio",
    equipment: "Rameur",
    location: "Salle",
    mode: "steps",
    measurementType: "duration_distance",
    media: officialExerciseMedia("rameur"),
    technique: "Commence jambes fléchies et bras tendus. Pousse d'abord avec les jambes, ouvre ensuite légèrement le buste puis termine en tirant la poignée vers le bas des côtes. Reviens dans l'ordre inverse.",
    description: "Appareil cardio sollicitant simultanément les jambes, le dos et les bras.",
    advice: "La poussée des jambes doit initier le mouvement. Évite de tirer trop tôt avec les bras ou d'arrondir fortement le dos.",
    muscles: ["Quadriceps", "Fessiers", "Dos", "Bras", "Cardio-respiratoire"],
    status: "active",
    createdAt,
    updatedAt: createdAt,
  },

  // ==========================================================
  // MOBILITÉ
  // ==========================================================
  {
    id: "import-marche",
    name: "Marche",
    category: "Cardio",
    equipment: "Poids du corps",
    location: "Maison",
    mode: "simple",
    measurementType: "distance",
    media: officialExerciseMedia("import-marche"),
    technique: "Marche d'un pas régulier et soutenu, buste droit, regard loin devant, bras qui balancent naturellement. Attaque le sol par le talon et déroule le pied jusqu'aux orteils.",
    description: "Activité d'endurance douce, en extérieur ou sur tapis, mesurée par la distance parcourue. Complète les séances de musculation sans fatigue supplémentaire.",
    advice: "Vise une allure où tu peux parler mais pas chanter (environ 5 à 6 km/h). Commence par 3 à 5 km et augmente la distance avant l'allure.",
    muscles: ["Quadriceps", "Ischio-jambiers", "Mollets", "Fessiers", "Cardio-respiratoire"],
    status: "active",
    createdAt,
    updatedAt: createdAt,
  },
  {
    id: "mobilite-chat-vache",
    name: "Chat-vache",
    category: "Mobilité",
    location: "Maison",
    mode: "series",
    measurementType: "reps",
    media: officialExerciseMedia("mobilite-chat-vache"),
    technique: "Place-toi à quatre pattes, mains sous les épaules et genoux sous les hanches. Alterne lentement entre l'arrondissement du dos et son extension en laissant le bassin et la tête accompagner le mouvement.",
    description: "Exercice de mobilité dynamique de la colonne vertébrale.",
    advice: "Effectue le mouvement lentement et sans chercher une amplitude forcée. Coordonne si possible le mouvement avec la respiration.",
    muscles: ["Colonne vertébrale", "Abdominaux", "Muscles du dos"],
    status: "active",
    createdAt,
    updatedAt: createdAt,
  },
  {
    id: "mobilite-rotation-thoracique",
    name: "Rotation thoracique à quatre pattes",
    category: "Mobilité",
    location: "Maison",
    mode: "series",
    measurementType: "reps_per_side",
    media: officialExerciseMedia("mobilite-rotation-thoracique"),
    technique: "À quatre pattes, place une main derrière la tête. Oriente le coude vers le sol puis tourne le haut du corps pour diriger le coude vers le plafond sans déplacer fortement le bassin.",
    description: "Exercice destiné à améliorer la mobilité en rotation de la partie thoracique de la colonne.",
    advice: "Cherche la rotation dans le haut du dos plutôt qu'en tournant le bassin. Réalise le mouvement des deux côtés.",
    muscles: ["Colonne thoracique", "Obliques", "Muscles du dos"],
    status: "active",
    createdAt,
    updatedAt: createdAt,
  },
  {
    id: "mobilite-flechisseur-hanche",
    name: "Étirement fléchisseur hanche en fente",
    category: "Mobilité",
    location: "Maison",
    mode: "series",
    measurementType: "duration_per_side",
    media: officialExerciseMedia("mobilite-flechisseur-hanche"),
    technique: "Place un genou au sol et l'autre pied devant toi en position de fente. Garde le buste droit et avance légèrement le bassin jusqu'à sentir un étirement à l'avant de la hanche de la jambe arrière.",
    description: "Étirement destiné à améliorer la mobilité des fléchisseurs de hanche.",
    advice: "Évite de cambrer le bas du dos pour gagner artificiellement de l'amplitude. Contracte légèrement le fessier de la jambe arrière.",
    muscles: ["Fléchisseurs de hanche", "Psoas", "Quadriceps"],
    status: "active",
    createdAt,
    updatedAt: createdAt,
  },
  {
    id: "mobilite-ischio-jambiers",
    name: "Étirement ischio-jambiers",
    category: "Mobilité",
    location: "Maison",
    mode: "series",
    measurementType: "duration_per_side",
    media: officialExerciseMedia("mobilite-ischio-jambiers"),
    technique: "Place une jambe devant toi et tends-la sans verrouiller fortement le genou. Incline progressivement le bassin vers l'avant en gardant le dos relativement neutre jusqu'à sentir l'étirement derrière la cuisse.",
    description: "Étirement destiné à améliorer la souplesse de l'arrière de la cuisse.",
    advice: "Ne cherche pas à atteindre le pied à tout prix. L'étirement doit rester progressif et contrôlé.",
    muscles: ["Ischio-jambiers", "Mollets"],
    status: "active",
    createdAt,
    updatedAt: createdAt,
  },
  {
    id: "mobilite-figure-4",
    name: "Étirement fessier / figure 4",
    category: "Mobilité",
    location: "Maison",
    mode: "series",
    measurementType: "duration_per_side",
    media: officialExerciseMedia("mobilite-figure-4"),
    technique: "Allonge-toi sur le dos et place une cheville sur la cuisse opposée. Ramène progressivement la jambe d'appui vers toi jusqu'à sentir l'étirement dans la fesse.",
    description: "Étirement en figure 4 destiné principalement à la mobilité des hanches et des fessiers.",
    advice: "Garde la tête et les épaules détendues. Ne pousse pas fortement sur le genou de la jambe croisée.",
    muscles: ["Fessiers", "Piriforme", "Hanche"],
    status: "active",
    createdAt,
    updatedAt: createdAt,
  },
  {
    id: "mobilite-cheville-genou-mur",
    name: "Mobilité cheville genou-au-mur",
    category: "Mobilité",
    location: "Maison",
    mode: "series",
    measurementType: "reps_per_side",
    media: officialExerciseMedia("mobilite-cheville-genou-mur"),
    technique: "Place le pied à plat face à un mur. Avance le genou vers le mur en le dirigeant dans l'axe du pied tout en gardant le talon au sol, puis reviens.",
    description: "Exercice de mobilité de cheville travaillant principalement la flexion de la cheville.",
    advice: "Le talon doit rester en contact avec le sol. Éloigne progressivement le pied du mur uniquement si le mouvement reste propre.",
    muscles: ["Cheville", "Mollets", "Soléaire"],
    status: "active",
    createdAt,
    updatedAt: createdAt,
  },
  {
    id: "mobilite-ouverture-epaules-mur",
    name: "Ouverture épaules / pectoraux au mur",
    category: "Mobilité",
    location: "Maison",
    mode: "series",
    measurementType: "duration_per_side",
    media: officialExerciseMedia("mobilite-ouverture-epaules-mur"),
    technique: "Place la main ou l'avant-bras contre un mur, bras ouvert sur le côté. Tourne doucement le buste dans la direction opposée jusqu'à sentir un étirement à l'avant de l'épaule et de la poitrine.",
    description: "Étirement destiné à améliorer l'ouverture des épaules et de la poitrine.",
    advice: "Ne force pas l'épaule en fin d'amplitude. Ajuste la hauteur du bras pour trouver une position confortable.",
    muscles: ["Pectoraux", "Épaules", "Biceps"],
    status: "active",
    createdAt,
    updatedAt: createdAt,
  },
  {
    id: "mobilite-rotation-golf",
    name: "Rotation tronc / hanches spécifique golf",
    category: "Mobilité",
    location: "Maison",
    mode: "series",
    measurementType: "reps_per_side",
    media: officialExerciseMedia("mobilite-rotation-golf"),
    technique: "Place-toi debout, pieds stables et genoux légèrement fléchis. Tourne progressivement le thorax et le bassin comme dans un mouvement de golf, puis reviens et répète de l'autre côté.",
    description: "Exercice de mobilité en rotation du tronc et des hanches adapté aux mouvements utilisés au golf.",
    advice: "Recherche un mouvement fluide plutôt qu'une rotation maximale. Garde les appuis stables et évite les mouvements brusques.",
    muscles: ["Obliques", "Hanches", "Colonne thoracique", "Fessiers"],
    status: "active",
    createdAt,
    updatedAt: createdAt,
  },

  // ==========================================================
  // TESTS DE MOBILITÉ
  // ==========================================================
  {
    id: "import-position-enfant",
    name: "Position de l'enfant",
    category: "Mobilité",
    location: "Maison",
    mode: "series",
    measurementType: "duration",
    media: officialExerciseMedia("import-position-enfant"),
    technique: "À genoux sur le tapis, gros orteils joints et genoux légèrement écartés, assieds-toi vers les talons et allonge les bras devant toi, front vers le sol. Respire lentement et laisse le dos s'allonger à chaque expiration.",
    description: "Posture de détente qui étire le bas du dos, les hanches et les épaules. Idéale en fin de séance ou entre deux exercices exigeants pour le dos.",
    advice: "Ne force jamais : si les fesses ne touchent pas les talons, reste où c'est confortable. Un coussin sous les genoux ou sous le front est bienvenu. Garde une respiration lente et profonde.",
    muscles: ["Lombaires", "Grands dorsaux", "Fessiers", "Hanches"],
    status: "active",
    createdAt,
    updatedAt: createdAt,
  },
  {
    id: "import-rotation-dos-allonge",
    name: "Rotation du dos allongé",
    category: "Mobilité",
    location: "Maison",
    mode: "series",
    measurementType: "duration_per_side",
    media: officialExerciseMedia("import-rotation-dos-allonge"),
    technique: "Allongé sur le dos, genoux pliés et pieds au sol, bras en croix. Laisse lentement tomber les deux genoux d'un côté jusqu'à la limite confortable, épaules au sol, tiens la position, puis ramène les genoux au centre et passe de l'autre côté.",
    description: "Mobilité en rotation de la colonne lombaire et thoracique, en douceur et sans charge. Relâche le bas du dos après les exercices assis ou de tirage.",
    advice: "Les deux épaules restent au contact du sol : c'est une rotation, pas un roulement. Ne descends pas au-delà de la sensation d'étirement ; expire quand les genoux descendent.",
    muscles: ["Lombaires", "Obliques", "Fessiers"],
    status: "active",
    createdAt,
    updatedAt: createdAt,
  },
  /* Lot K.0 (25/09/2026) : étirements des routines du soir absents du catalogue. */
  {
    id: "etirement-epaule-main-dos",
    name: "Étirement de l'épaule, main dans le dos",
    category: "Mobilité",
    location: "Maison",
    mode: "series",
    measurementType: "duration_per_side",
    technique: "Debout, passe une main dans le dos et remonte-la doucement le long de la colonne ; l'autre main peut tirer légèrement sur le poignet. Tiens la position en respirant.",
    description: "Étirement de l'avant et de l'arrière de l'épaule, main dans le dos.",
    advice: "Reste dans une sensation d'étirement, jamais de douleur. Garde les épaules basses.",
    muscles: ["Épaules", "Coiffe des rotateurs"],
    status: "active",
    createdAt,
    updatedAt: createdAt,
  },

  {
    id: "papillon-assis",
    name: "Papillon assis",
    category: "Mobilité",
    location: "Maison",
    mode: "series",
    measurementType: "duration",
    technique: "Assis, plantes des pieds l'une contre l'autre, talons ramenés vers toi. Garde le dos droit et laisse les genoux descendre sans forcer.",
    description: "Étirement de l'intérieur des cuisses et des hanches.",
    advice: "Ne pousse pas sur les genoux ; respire et laisse la position se relâcher.",
    muscles: ["Adducteurs", "Hanches"],
    status: "active",
    createdAt,
    updatedAt: createdAt,
  },

  {
    id: "test-doigts-sol",
    name: "Doigts-sol",
    category: "Test mobilité",
    location: "Maison",
    mode: "simple",
    measurementType: "distance_cm",
    media: officialExerciseMedia("test-doigts-sol"),
    measurementLabels: {
      value: "Distance doigts-sol",
    },
    technique: "Debout, pieds parallèles et jambes tendues sans verrouiller fortement les genoux. Penche lentement le buste vers l'avant et laisse les bras descendre vers le sol. Mesure verticalement la distance entre le bout des doigts et le sol.",
    description: "Test de flexion avant permettant de suivre simplement l'évolution de la mobilité de la chaîne postérieure.",
    advice: "Utilise toujours la même position des pieds et les mêmes conditions. Valeur positive si les doigts restent au-dessus du sol, 0 cm s'ils touchent le sol et valeur négative s'ils dépassent le niveau du sol.",
    muscles: ["Ischio-jambiers", "Mollets", "Muscles du dos"],
    status: "active",
    createdAt,
    updatedAt: createdAt,
  },
  {
    id: "test-apley",
    name: "Mains dans le dos",
    category: "Test mobilité",
    location: "Maison",
    mode: "simple",
    measurementType: "distance_cm_per_side",
    media: officialExerciseMedia("test-apley"),
    measurementLabels: {
      left: "Bras gauche en haut",
      right: "Bras droit en haut",
    },
    technique: "Place un bras au-dessus de l'épaule et derrière le dos, et l'autre bras derrière le dos depuis le bas. Rapproche les mains sans forcer et mesure la distance entre les extrémités des doigts. Effectue ensuite le test en inversant les bras.",
    description: "Test de mobilité des épaules mesurant la capacité des deux mains à se rapprocher derrière le dos.",
    advice: "Mesure les deux configurations séparément. Valeur positive s'il reste un espace entre les doigts, 0 cm s'ils se touchent et valeur négative si les doigts se chevauchent. Ne force pas l'épaule pour améliorer artificiellement la mesure.",
    muscles: ["Épaules", "Coiffe des rotateurs", "Pectoraux", "Grand dorsal"],
    status: "active",
    createdAt,
    updatedAt: createdAt,
  },
  {
    id: "test-papillon",
    name: "Papillon",
    category: "Test mobilité",
    location: "Maison",
    mode: "simple",
    measurementType: "distance_cm_per_side",
    media: officialExerciseMedia("test-papillon"),
    measurementLabels: {
      left: "Genou gauche",
      right: "Genou droit",
    },
    technique: "Assieds-toi avec les plantes de pieds l'une contre l'autre et laisse les genoux descendre naturellement vers les côtés. Mesure verticalement la distance entre chaque genou et le sol.",
    description: "Test permettant de suivre l'évolution de la mobilité des hanches en position papillon.",
    advice: "Garde autant que possible la même distance entre les talons et le bassin à chaque mesure. Ne pousse pas les genoux avec les mains. La valeur minimale est 0 cm lorsque le genou atteint le sol.",
    muscles: ["Adducteurs", "Hanches", "Aine"],
    status: "active",
    createdAt,
    updatedAt: createdAt,
  },
] satisfies Exercise[];
